check:
  - HIGH
  - CRITICAL
skip-check:
  - CKV_AWS_111 # We'll fix Flow Logs later
  - CKV_DOCKER_2 # Skip "Healthcheck" requirement for now
framework:
  - cloudformation
  - dockercompose
  - ansible